import fs from 'fs-extra';

const config = `# Generated By RiVE
name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run build
`;

export function initGitHubCI() {
  fs.outputFileSync('.github/workflows/ci.yml', config);
}
